import './globals.css';
import type { Metadata } from 'next';

import SideBar from '@/components/Bar/SideBar';
import TopBar from '@/components/Bar/TopBar';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <TopBar />
        {children}
      </body>
    </html>
  )
}
