import './globals.css';
import type { Metadata } from 'next';

import SideBar from '@/components/Bar/SideBar';
import TopBar from '@/components/Bar/TopBar';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="flex">
        <div className="w-1/5">
          <SideBar />
        </div>
        <div className="w-[80%] mt-2 relative">
          <TopBar />
          <main className="mt-16 container px-4 m-2">
            {children}
          </main>
        </div>
      </body>
    </html>
  )
}
